import { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextJs login Page",
  description: "Generated by create next app",
};

export default function Login() {
  return <h1>Login</h1>;
}
